# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.2.2/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.2.2/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/takuma/github/picam360-driver

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/takuma/github/picam360-driver

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.2.2/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.2.2/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/takuma/github/picam360-driver/CMakeFiles /Users/takuma/github/picam360-driver/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/takuma/github/picam360-driver/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named picam360-driver.bin

# Build rule for target.
picam360-driver.bin: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 picam360-driver.bin
.PHONY : picam360-driver.bin

# fast build rule for target.
picam360-driver.bin/fast:
	$(MAKE) -f CMakeFiles/picam360-driver.bin.dir/build.make CMakeFiles/picam360-driver.bin.dir/build
.PHONY : picam360-driver.bin/fast

manual_mpu.o: manual_mpu.c.o
.PHONY : manual_mpu.o

# target to build an object file
manual_mpu.c.o:
	$(MAKE) -f CMakeFiles/picam360-driver.bin.dir/build.make CMakeFiles/picam360-driver.bin.dir/manual_mpu.c.o
.PHONY : manual_mpu.c.o

manual_mpu.i: manual_mpu.c.i
.PHONY : manual_mpu.i

# target to preprocess a source file
manual_mpu.c.i:
	$(MAKE) -f CMakeFiles/picam360-driver.bin.dir/build.make CMakeFiles/picam360-driver.bin.dir/manual_mpu.c.i
.PHONY : manual_mpu.c.i

manual_mpu.s: manual_mpu.c.s
.PHONY : manual_mpu.s

# target to generate assembly for a file
manual_mpu.c.s:
	$(MAKE) -f CMakeFiles/picam360-driver.bin.dir/build.make CMakeFiles/picam360-driver.bin.dir/manual_mpu.c.s
.PHONY : manual_mpu.c.s

mrevent.o: mrevent.c.o
.PHONY : mrevent.o

# target to build an object file
mrevent.c.o:
	$(MAKE) -f CMakeFiles/picam360-driver.bin.dir/build.make CMakeFiles/picam360-driver.bin.dir/mrevent.c.o
.PHONY : mrevent.c.o

mrevent.i: mrevent.c.i
.PHONY : mrevent.i

# target to preprocess a source file
mrevent.c.i:
	$(MAKE) -f CMakeFiles/picam360-driver.bin.dir/build.make CMakeFiles/picam360-driver.bin.dir/mrevent.c.i
.PHONY : mrevent.c.i

mrevent.s: mrevent.c.s
.PHONY : mrevent.s

# target to generate assembly for a file
mrevent.c.s:
	$(MAKE) -f CMakeFiles/picam360-driver.bin.dir/build.make CMakeFiles/picam360-driver.bin.dir/mrevent.c.s
.PHONY : mrevent.c.s

picam360_driver.o: picam360_driver.c.o
.PHONY : picam360_driver.o

# target to build an object file
picam360_driver.c.o:
	$(MAKE) -f CMakeFiles/picam360-driver.bin.dir/build.make CMakeFiles/picam360-driver.bin.dir/picam360_driver.c.o
.PHONY : picam360_driver.c.o

picam360_driver.i: picam360_driver.c.i
.PHONY : picam360_driver.i

# target to preprocess a source file
picam360_driver.c.i:
	$(MAKE) -f CMakeFiles/picam360-driver.bin.dir/build.make CMakeFiles/picam360-driver.bin.dir/picam360_driver.c.i
.PHONY : picam360_driver.c.i

picam360_driver.s: picam360_driver.c.s
.PHONY : picam360_driver.s

# target to generate assembly for a file
picam360_driver.c.s:
	$(MAKE) -f CMakeFiles/picam360-driver.bin.dir/build.make CMakeFiles/picam360-driver.bin.dir/picam360_driver.c.s
.PHONY : picam360_driver.c.s

quaternion.o: quaternion.c.o
.PHONY : quaternion.o

# target to build an object file
quaternion.c.o:
	$(MAKE) -f CMakeFiles/picam360-driver.bin.dir/build.make CMakeFiles/picam360-driver.bin.dir/quaternion.c.o
.PHONY : quaternion.c.o

quaternion.i: quaternion.c.i
.PHONY : quaternion.i

# target to preprocess a source file
quaternion.c.i:
	$(MAKE) -f CMakeFiles/picam360-driver.bin.dir/build.make CMakeFiles/picam360-driver.bin.dir/quaternion.c.i
.PHONY : quaternion.c.i

quaternion.s: quaternion.c.s
.PHONY : quaternion.s

# target to generate assembly for a file
quaternion.c.s:
	$(MAKE) -f CMakeFiles/picam360-driver.bin.dir/build.make CMakeFiles/picam360-driver.bin.dir/quaternion.c.s
.PHONY : quaternion.c.s

rtp.o: rtp.cc.o
.PHONY : rtp.o

# target to build an object file
rtp.cc.o:
	$(MAKE) -f CMakeFiles/picam360-driver.bin.dir/build.make CMakeFiles/picam360-driver.bin.dir/rtp.cc.o
.PHONY : rtp.cc.o

rtp.i: rtp.cc.i
.PHONY : rtp.i

# target to preprocess a source file
rtp.cc.i:
	$(MAKE) -f CMakeFiles/picam360-driver.bin.dir/build.make CMakeFiles/picam360-driver.bin.dir/rtp.cc.i
.PHONY : rtp.cc.i

rtp.s: rtp.cc.s
.PHONY : rtp.s

# target to generate assembly for a file
rtp.cc.s:
	$(MAKE) -f CMakeFiles/picam360-driver.bin.dir/build.make CMakeFiles/picam360-driver.bin.dir/rtp.cc.s
.PHONY : rtp.cc.s

video_mjpeg.o: video_mjpeg.cc.o
.PHONY : video_mjpeg.o

# target to build an object file
video_mjpeg.cc.o:
	$(MAKE) -f CMakeFiles/picam360-driver.bin.dir/build.make CMakeFiles/picam360-driver.bin.dir/video_mjpeg.cc.o
.PHONY : video_mjpeg.cc.o

video_mjpeg.i: video_mjpeg.cc.i
.PHONY : video_mjpeg.i

# target to preprocess a source file
video_mjpeg.cc.i:
	$(MAKE) -f CMakeFiles/picam360-driver.bin.dir/build.make CMakeFiles/picam360-driver.bin.dir/video_mjpeg.cc.i
.PHONY : video_mjpeg.cc.i

video_mjpeg.s: video_mjpeg.cc.s
.PHONY : video_mjpeg.s

# target to generate assembly for a file
video_mjpeg.cc.s:
	$(MAKE) -f CMakeFiles/picam360-driver.bin.dir/build.make CMakeFiles/picam360-driver.bin.dir/video_mjpeg.cc.s
.PHONY : video_mjpeg.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... picam360-driver.bin"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... manual_mpu.o"
	@echo "... manual_mpu.i"
	@echo "... manual_mpu.s"
	@echo "... mrevent.o"
	@echo "... mrevent.i"
	@echo "... mrevent.s"
	@echo "... picam360_driver.o"
	@echo "... picam360_driver.i"
	@echo "... picam360_driver.s"
	@echo "... quaternion.o"
	@echo "... quaternion.i"
	@echo "... quaternion.s"
	@echo "... rtp.o"
	@echo "... rtp.i"
	@echo "... rtp.s"
	@echo "... video_mjpeg.o"
	@echo "... video_mjpeg.i"
	@echo "... video_mjpeg.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

